# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mauricesam:
    image: mauricesam
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5052:5052
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
